### ISSUE TITLE
So,the STDCSeg is the best balance of speed and acc without distillation?

### ISSUE THREAD

**Issue by ezio1320** [zh320/realtime-semantic-segmentation-pytorch#18]
Thank you for the nice code and comparsion of the real-time segmentation methods, Is the STDCseg is the best method? In other words,   if i have a new segmentation job to do, Can i choose STDCSeg brainlessly？

（所以说STDC是目前最牛逼的实时语义分割方法哈？ 可以无脑用吧）

**Comment by zh320** [comment]
It's hard to say which one is the best. As I said, the tested FPSs depend on many factors, such as different hardware, whether to use cudnn or not etc. In my experiments, without pre-training the backbone, STDC didn't reach reported results (<74%). Indeed, these performances were obtained by using deep supervision (i.e. auxiliary heads). In the same experiment setting, such as DDRNet, FarseeNet should achieve similar performance.

Best
