### ISSUE TITLE
I can't run without smp

### ISSUE THREAD

**Issue by chris2000520** [zh320/realtime-semantic-segmentation-pytorch#5]
I can't run main.py because it tells me I'm missing the smp module, but I don't want to use smp

**Comment by zh320** [comment]
Hi, Chris, if you don't want to use smp, you can comment the following lines

https://github.com/zh320/realtime-semantic-segmentation-pytorch/blob/fc257a9a103080cb78bab2cf99c9869c41835a88/models/__init__.py#L2

https://github.com/zh320/realtime-semantic-segmentation-pytorch/blob/fc257a9a103080cb78bab2cf99c9869c41835a88/models/__init__.py#L41

**Comment by chris2000520** [comment]
> Hi, Chris, if you don't want to use smp, you can comment the following lines
> 
> https://github.com/zh320/realtime-semantic-segmentation-pytorch/blob/fc257a9a103080cb78bab2cf99c9869c41835a88/models/__init__.py#L2
> 
> https://github.com/zh320/realtime-semantic-segmentation-pytorch/blob/fc257a9a103080cb78bab2cf99c9869c41835a88/models/__init__.py#L41

oh！it works！Thank U！
